version: '3.8'

services:
  hate-speech-app:
    build: .
    container_name: hate-speech-detector
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount logs directory (optional)
      - ./logs:/app/logs
    networks:
      - hate-speech-network

networks:
  hate-speech-network:
    driver: bridge
